package com.fatec.teste;

//Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;

public class UC01ConsultaCEP {
	private WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;

	@Before
	public void setUp() {
		System.setProperty("webdriver.chrome.driver", "browserDriver/chromedriver");
		driver = new ChromeDriver();
		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();
	}

	@After
	public void tearDown() {
		driver.quit();
	}

	@Test
	public void cT01ConsultaComSucesso() {
		driver.get("http://www.buscacep.correios.com.br/sistemas/buscacep/buscaCep.cfm");
		{
			WebElement dropdown = driver.findElement(By.name("UF"));
			dropdown.findElement(By.xpath("//option[. = 'SP']")).click();
		}
		driver.findElement(By.name("Localidade")).sendKeys("São Paulo");
		{
			WebElement dropdown = driver.findElement(By.name("Tipo"));
			dropdown.findElement(By.xpath("//option[. = 'Rua']")).click();
		}
		driver.findElement(By.name("Logradouro")).sendKeys("Frei Joao");
		driver.findElement(By.cssSelector(".btn2")).click();
		espera();
		assertThat(driver.findElement(By.cssSelector("p")).getText(), is("DADOS ENCONTRADOS COM SUCESSO."));
	}

	@Test
	public void cT02ConsultaCEPcomLogradouroInvalido() {
		driver.get("http://www.buscacep.correios.com.br/sistemas/buscacep/buscaCep.cfm");
		{
			WebElement dropdown = driver.findElement(By.name("UF"));
			dropdown.findElement(By.xpath("//option[. = 'SP']")).click();
		}
		driver.findElement(By.name("Localidade")).sendKeys("São Paulo");
		{
			WebElement dropdown = driver.findElement(By.name("Tipo"));
			dropdown.findElement(By.xpath("//option[. = 'Rua']")).click();
		}
		driver.findElement(By.name("Logradouro")).sendKeys("xxxxxx");
		driver.findElement(By.cssSelector(".btn2")).click();
		espera();
		assertThat(driver.findElement(By.cssSelector("p")).getText(), is("LOGRADOURO NAO ENCONTRADO."));
	}

	@Test
	public void cT03ConsultaCEPcomLogradouroEmBranco() {
		driver.get("http://www.buscacep.correios.com.br/sistemas/buscacep/buscaCep.cfm");
		{
			WebElement dropdown = driver.findElement(By.name("UF"));
			dropdown.findElement(By.xpath("//option[. = 'SP']")).click();
		}
		driver.findElement(By.name("Localidade")).sendKeys("São Paulo");
		{
			WebElement dropdown = driver.findElement(By.name("Tipo"));
			dropdown.findElement(By.xpath("//option[. = 'Rua']")).click();
		}
		driver.findElement(By.cssSelector(".btn2")).click();
		espera();
		assertThat(driver.switchTo().alert().getText(), is("Informe o logradouro !"));
	}

	@Test
	public void cT04ConsultaCEPcomLogradouroInvalido() {
		driver.get("http://www.buscacep.correios.com.br/sistemas/buscacep/buscaCep.cfm");
		{
			WebElement dropdown = driver.findElement(By.name("UF"));
			dropdown.findElement(By.xpath("//option[. = 'SP']")).click();
		}
		driver.findElement(By.name("Localidade")).sendKeys("São Paulo");
		{
			WebElement dropdown = driver.findElement(By.name("Tipo"));
			dropdown.findElement(By.xpath("//option[. = 'Rua']")).click();
		}
		driver.findElement(By.name("Logradouro")).sendKeys("&%%%%");
		driver.findElement(By.cssSelector(".btn2")).click();
		espera();
		assertThat(driver.findElement(By.cssSelector("p")).getText(), is("LOGRADOURO NAO INFORMADO/INVALIDO"));
	}

	public void espera() {
		try {
			Thread.sleep(1000);
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
	}
}
